image:
  file: .gitpod.dockerfile
tasks:
- init: git submodule init; git submodule update
  command: >
    cp .mailmap ./theia &
    ./gitstats ./theia /tmp/stats &
    gp open /tmp/stats/index.html
    yarn --cwd examples/browser start ../.. --hostname=0.0.0.0
